# Generated by Django 3.2.5 on 2022-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=1000)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
    ]
